### ISSUE TITLE
Type check and code generation for let expression is broken

### ISSUE THREAD

**Issue by phenax** [eeue56/derw#10]
I was experimenting with the language on the [playground](https://www.derw-lang.com/playground/) and tested out the following code

```elm
fn: number -> string
fn =
    let y = 0
    in y
```

## Expected
- The example above should error out since the inferred type and the annotated type do not unify
- The generated code should be valid typescript

## Observed
Results in the following code which is invalid.

```elm
function fn(_0: number): string {
    return y;
}
```

The value given to y doesn't matter since it seems to be completely ignored.

**Comment by eeue56** [comment]
Nice! Thanks for the report. The type inference is a work in progress at the moment - but this one should be an easy fix.

**Comment by janwirth** [comment]
I also think the examples should not compile due to mismatch number of arguments in signature and definition.

**Comment by eeue56** [comment]
This is an error now: 

```
Expected `string` but got `number` in the body of the function:

fn: number -> string 
fn x = 
    let 
        y: number 
        y = 0
    in 
        y
```

Mismatching number of arguments in signature vs definition is kinda intended currently
