### ISSUE TITLE
Type error in case expression not reported

### ISSUE THREAD

**Issue by ayazhafiz** [eeue56/derw#12]
Firstly, cool project. Thanks for making it public and writing about it!

I believe the following code should yield a type error, but it doesn't (at least on the playground)

```
type Result a b
    = Err { error: a }
    | Ok { value: b }

f : Result a b -> Result a b
f result =
    case result of
        Er { error } -> E { error }
        O { value } -> O { value }
```

**Comment by eeue56** [comment]
Hi there! The build on playground runs a little behind the released version on npm. Currently that code would give you the following error message:

Error on lines 4 - 9
The case statement did not match the union Result (a b)
All possible branches of a union must be covered. I expected a branch for Err | Ok but they were missing. If you don't need one, have a default branch
I got too many branches. The branches for Er | O aren't part of the union so will never be true. Remove them.:
```
f : Result a b -> Result a b
f result =
    case result of
        Er { error } -> E { error }
        O { value } -> O { value }
```


The error message for the body of the branch currently doesn't do type checking, but it's on my to-do list to add that.
