### ISSUE TITLE
Where to go for questions?

### ISSUE THREAD

**Issue by adamwong246** [eeue56/derw#13]
I know issues isn't really the right place for this but I am trying to fins some answer to questions about this project. Could we open up the discussions GH feature? Or maybe a discord or something like that?

**Comment by eeue56** [comment]
Hi!

There's a Zulip chat: https://derw.zulipchat.com/join/4bfr6yyf7ow75eya4hmztx6g/

That's the place to go right now, or Twitter.

**Comment by adamwong246** [comment]
twitter would not allow me to DM you. My account may have been blacklisted for inactivity?

**Comment by eeue56** [comment]
Discussions is enabled now for anyone looking for a forum to discuss in: https://github.com/eeue56/derw/discussions
